ALTER TABLE products ADD COLUMN IF NOT EXISTS proposal_status VARCHAR(20) NOT NULL DEFAULT 'approved';
ALTER TABLE products ADD COLUMN IF NOT EXISTS proposed_by_staff_id INTEGER REFERENCES staff(id) ON DELETE SET NULL;
